/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardAdminIndexRouteImport } from './routes/_dashboard/admin.index'
import { Route as DashboardAccountIndexRouteImport } from './routes/_dashboard.account.index'
import { Route as DashboardCSlugRouteImport } from './routes/_dashboard/c.$slug'
import { Route as DashboardAdminWorkspacesRouteImport } from './routes/_dashboard/admin.workspaces'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard/admin.users'
import { Route as DashboardAccountSecurityRouteImport } from './routes/_dashboard.account.security'
import { Route as DashboardAccountProfileRouteImport } from './routes/_dashboard.account.profile'
import { Route as DashboardCSlugIndexRouteImport } from './routes/_dashboard/c.$slug.index'
import { Route as DashboardCSlugSqlEditorRouteImport } from './routes/_dashboard/c.$slug.sql-editor'
import { Route as DashboardCSlugSettingsRouteImport } from './routes/_dashboard/c.$slug.settings'
import { Route as DashboardCSlugMembersRouteImport } from './routes/_dashboard/c.$slug.members'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCSlugRoute = DashboardCSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminWorkspacesRoute =
  DashboardAdminWorkspacesRouteImport.update({
    id: '/admin/workspaces',
    path: '/admin/workspaces',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountSecurityRoute =
  DashboardAccountSecurityRouteImport.update({
    id: '/account/security',
    path: '/account/security',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountProfileRoute = DashboardAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCSlugIndexRoute = DashboardCSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardCSlugRoute,
} as any)
const DashboardCSlugSqlEditorRoute = DashboardCSlugSqlEditorRouteImport.update({
  id: '/sql-editor',
  path: '/sql-editor',
  getParentRoute: () => DashboardCSlugRoute,
} as any)
const DashboardCSlugSettingsRoute = DashboardCSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardCSlugRoute,
} as any)
const DashboardCSlugMembersRoute = DashboardCSlugMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardCSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof DashboardProfileRoute
  '/account/profile': typeof DashboardAccountProfileRoute
  '/account/security': typeof DashboardAccountSecurityRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/admin/workspaces': typeof DashboardAdminWorkspacesRoute
  '/c/$slug': typeof DashboardCSlugRouteWithChildren
  '/account': typeof DashboardAccountIndexRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/c/$slug/members': typeof DashboardCSlugMembersRoute
  '/c/$slug/settings': typeof DashboardCSlugSettingsRoute
  '/c/$slug/sql-editor': typeof DashboardCSlugSqlEditorRoute
  '/c/$slug/': typeof DashboardCSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof DashboardProfileRoute
  '/account/profile': typeof DashboardAccountProfileRoute
  '/account/security': typeof DashboardAccountSecurityRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/admin/workspaces': typeof DashboardAdminWorkspacesRoute
  '/account': typeof DashboardAccountIndexRoute
  '/admin': typeof DashboardAdminIndexRoute
  '/c/$slug/members': typeof DashboardCSlugMembersRoute
  '/c/$slug/settings': typeof DashboardCSlugSettingsRoute
  '/c/$slug/sql-editor': typeof DashboardCSlugSqlEditorRoute
  '/c/$slug': typeof DashboardCSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/account/profile': typeof DashboardAccountProfileRoute
  '/_dashboard/account/security': typeof DashboardAccountSecurityRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/_dashboard/admin/workspaces': typeof DashboardAdminWorkspacesRoute
  '/_dashboard/c/$slug': typeof DashboardCSlugRouteWithChildren
  '/_dashboard/account/': typeof DashboardAccountIndexRoute
  '/_dashboard/admin/': typeof DashboardAdminIndexRoute
  '/_dashboard/c/$slug/members': typeof DashboardCSlugMembersRoute
  '/_dashboard/c/$slug/settings': typeof DashboardCSlugSettingsRoute
  '/_dashboard/c/$slug/sql-editor': typeof DashboardCSlugSqlEditorRoute
  '/_dashboard/c/$slug/': typeof DashboardCSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/account/profile'
    | '/account/security'
    | '/admin/users'
    | '/admin/workspaces'
    | '/c/$slug'
    | '/account'
    | '/admin'
    | '/c/$slug/members'
    | '/c/$slug/settings'
    | '/c/$slug/sql-editor'
    | '/c/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/account/profile'
    | '/account/security'
    | '/admin/users'
    | '/admin/workspaces'
    | '/account'
    | '/admin'
    | '/c/$slug/members'
    | '/c/$slug/settings'
    | '/c/$slug/sql-editor'
    | '/c/$slug'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/profile'
    | '/_dashboard/account/profile'
    | '/_dashboard/account/security'
    | '/_dashboard/admin/users'
    | '/_dashboard/admin/workspaces'
    | '/_dashboard/c/$slug'
    | '/_dashboard/account/'
    | '/_dashboard/admin/'
    | '/_dashboard/c/$slug/members'
    | '/_dashboard/c/$slug/settings'
    | '/_dashboard/c/$slug/sql-editor'
    | '/_dashboard/c/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/': {
      id: '/_dashboard/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/': {
      id: '/_dashboard/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/c/$slug': {
      id: '/_dashboard/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof DashboardCSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/workspaces': {
      id: '/_dashboard/admin/workspaces'
      path: '/admin/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof DashboardAdminWorkspacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/security': {
      id: '/_dashboard/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof DashboardAccountSecurityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/account/profile': {
      id: '/_dashboard/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof DashboardAccountProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/c/$slug/': {
      id: '/_dashboard/c/$slug/'
      path: '/'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof DashboardCSlugIndexRouteImport
      parentRoute: typeof DashboardCSlugRoute
    }
    '/_dashboard/c/$slug/sql-editor': {
      id: '/_dashboard/c/$slug/sql-editor'
      path: '/sql-editor'
      fullPath: '/c/$slug/sql-editor'
      preLoaderRoute: typeof DashboardCSlugSqlEditorRouteImport
      parentRoute: typeof DashboardCSlugRoute
    }
    '/_dashboard/c/$slug/settings': {
      id: '/_dashboard/c/$slug/settings'
      path: '/settings'
      fullPath: '/c/$slug/settings'
      preLoaderRoute: typeof DashboardCSlugSettingsRouteImport
      parentRoute: typeof DashboardCSlugRoute
    }
    '/_dashboard/c/$slug/members': {
      id: '/_dashboard/c/$slug/members'
      path: '/members'
      fullPath: '/c/$slug/members'
      preLoaderRoute: typeof DashboardCSlugMembersRouteImport
      parentRoute: typeof DashboardCSlugRoute
    }
  }
}

interface DashboardCSlugRouteChildren {
  DashboardCSlugMembersRoute: typeof DashboardCSlugMembersRoute
  DashboardCSlugSettingsRoute: typeof DashboardCSlugSettingsRoute
  DashboardCSlugSqlEditorRoute: typeof DashboardCSlugSqlEditorRoute
  DashboardCSlugIndexRoute: typeof DashboardCSlugIndexRoute
}

const DashboardCSlugRouteChildren: DashboardCSlugRouteChildren = {
  DashboardCSlugMembersRoute: DashboardCSlugMembersRoute,
  DashboardCSlugSettingsRoute: DashboardCSlugSettingsRoute,
  DashboardCSlugSqlEditorRoute: DashboardCSlugSqlEditorRoute,
  DashboardCSlugIndexRoute: DashboardCSlugIndexRoute,
}

const DashboardCSlugRouteWithChildren = DashboardCSlugRoute._addFileChildren(
  DashboardCSlugRouteChildren,
)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardAccountProfileRoute: typeof DashboardAccountProfileRoute
  DashboardAccountSecurityRoute: typeof DashboardAccountSecurityRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminWorkspacesRoute: typeof DashboardAdminWorkspacesRoute
  DashboardCSlugRoute: typeof DashboardCSlugRouteWithChildren
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardAccountProfileRoute: DashboardAccountProfileRoute,
  DashboardAccountSecurityRoute: DashboardAccountSecurityRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminWorkspacesRoute: DashboardAdminWorkspacesRoute,
  DashboardCSlugRoute: DashboardCSlugRouteWithChildren,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
